/*DB Initialization */
INSERT INTO COUNTRY(ID, COMMON_NAME, BUYS, SELLS)
VALUES(1, 'France', 244, 554);

INSERT INTO COUNTRY(ID, COMMON_NAME, BUYS, SELLS)
VALUES(2, 'UK', 99, 669);

INSERT INTO COUNTRY(ID, COMMON_NAME, BUYS, SELLS)
VALUES(3, 'Italy', 123, 874);

INSERT INTO COUNTRY(ID, COMMON_NAME, BUYS, SELLS)
VALUES(4, 'Spain', 456, 64);

INSERT INTO COUNTRY(ID, COMMON_NAME, BUYS, SELLS)
VALUES(5, 'Belgium', 230, 32);

INSERT INTO COUNTRY(ID, COMMON_NAME, BUYS, SELLS)
VALUES(6, 'Canada', 150, 315);

INSERT INTO COUNTRY(ID, COMMON_NAME, BUYS, SELLS)
VALUES(7, 'Germany', 457, 54);

INSERT INTO COUNTRY(ID, COMMON_NAME, BUYS, SELLS)
VALUES(8, 'Portugal', 100, 43);